name: Docker Image CI

on: [push]
     # Environment variables available to all jobs and steps in this workflow
env: # Or as an environment variable
      docker_username: ${{ secrets.DOCKER_USER }}
      docker_password: ${{ secrets.DOCKER_PW }}

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Download workspace
      uses: actions/download-artifact@v1
      with:
        name: workspace
        path: .
    - name: Build the Docker image
      run: docker build -t bharamicrosystems/nginx:dev .
    - name: Login to Docker
      run: echo "$docker_password" | docker login -u "$docker_username" --password-stdin
    - name: Push the docker image
      run: docker push bharamicrosystems/nginx:dev

  kubernetes-component-test:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
    - name: Download workspace
      uses: actions/download-artifact@v1
      with:
        name: workspace
        path: .
    - name: Run KIND Test
      run: . build-test.sh
	  
  promote-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
    - name: Download workspace
      uses: actions/download-artifact@v1
      with:
        name: workspace
        path: .
    - name: Tag the Docker image
      run: docker tag bharamicrosystems/nginx:dev bharamicrosystems/nginx:release
    - name: Login to Docker
      run: echo "$docker_password" | docker login -u "$docker_username" --password-stdin
    - name: Push the docker image
      run: docker push bharamicrosystems/nginx:release
